SELECT ANCESTOR_CONCEPT_ID,
	DESCENDANT_CONCEPT_ID,
	MIN_LEVELS_OF_SEPARATION,
	MAX_LEVELS_OF_SEPARATION
FROM @vocabulary_database_schema.concept_ancestor
WHERE ANCESTOR_CONCEPT_ID IN (@concept_id_list)
	OR DESCENDANT_CONCEPT_ID IN (@concept_id_list);